### ISSUE TITLE
Word definitions

### ISSUE THREAD

**Issue by MrMethodmanMAN** [aido179/moggle#1]
Love the game Aidan. 
On a constructive note, definitions could be an added extra...

**Comment by jangerhofer** [comment]
#2 Is this the right idea, @MrMethodmanMAN ?  Clearly, it's an ugly solution, but I tried it out for the sake of a bit of Meteor learning!

**Comment by aido179** [comment]
Great contribution. Have left a comment on the PR with some suggestions / queries. 

I'd update it to only find a definition when a user asks for one, by clicking a define button for example.

**Comment by aido179** [comment]
I've merged @jangerhofer's [pull request](https://github.com/aido179/moggle/pull/2) and updated it inline with the comments I left yesterday.
